version: "3.5"

services:
  pingdataconsole:
    image:  pingidentity/pingdataconsole:2104-8.2.0.3
    env_file:
      - env-vars
    ports:
      - "9443:8443"
    networks:
      - pingnet

networks:
  pingnet:
    external: true
