version: "3.5"

services:
  pingdirectory:
    image: pingidentity/pingdirectory:2104-8.2.0.3
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
    env_file:
      - env-vars
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "1389:1389"
      - "1636:1636"
      - "1443:1443"
    networks:
      - pingnet
    volumes:
      - ./volume:/opt/out

networks:
  pingnet:
    external: true
