version: "3.5"

services:
  pingaccess:
    image: pingidentity/pingaccess:2006-6.1.0
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingfederate
    env_file:
      - env-vars
    ports:
      - "9000:9000"
    networks:
      - pingnet
    volumes:
      - ./volume:/opt/out

networks:
  pingnet:
    external: true
