version: "3.5"

services:
  pingfederate:
    image: pingidentity/pingfederate:2104-10.2.2
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingfederate
    env_file:
      - env-vars
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
    volumes:
      - ./volume:/opt/out

networks:
  pingnet:
    external: true
