version: "3.5"

services:
  pingdelegator:
    image: pingidentity/pingdelegator:4.2.1-alpine-edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdelegator
    env_file:
      - env-vars
    ports:
      - "6443:6443"
    networks:
      - pingnet

networks:
  pingnet:
    external: true
