version: "3.5"

services:
  pingdatagovernance:
    image: pingidentity/pingdatagovernance:2006-8.1.0.0
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdatagovernance
    env_file:
      - env-vars
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8080:80"
      - "7443:443"
    networks:
      - pingnet
    volumes:
      - ./volume:/opt/out

networks:
  pingnet:
    external: true
