version: "3.5"

services:
  pingdatagovernance:
    image: pingidentity/pingdatagovernance:2006-8.1.0.0
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pdg-pap-integration/pingdatagovernance
      - SERVER_PROFILE_PARENT=PDG
      - SERVER_PROFILE_PDG_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PDG_PATH=baseline/pingdatagovernance
    env_file:
      - env-vars
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8080:80"
      - "7389:389"
      - "7443:443"
      - "7636:636"
    networks:
      - pingnet
    volumes:
      - ./volume/pingdatagovernance:/opt/out

  pingdatagovernancepap:
    image: pingidentity/pingdatagovernancepap:2006-8.1.0.0
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=pdg-pap-integration/pingdatagovernancepap
      - HTTPS_PORT=8443
    env_file:
      - env-vars
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "8443:8443"
    networks:
      - pingnet
    volumes:
      - ./volume/pingdatagovernancepap:/opt/out

networks:
  pingnet:
    external: true
